DROP DATABASE IF EXISTS QUIZ;
CREATE DATABASE QUIZ;
USE QUIZ;

CREATE TABLE IF NOT EXISTS QUIZ(
	ID INT NOT NULL AUTO_INCREMENT,
    TITULO TEXT,
    DESCRICAO TEXT,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS PERGUNTA(
	ID INT NOT NULL AUTO_INCREMENT,
    ENUNCIADO TEXT,
    QUIZ INT,
    FOREIGN KEY (QUIZ) REFERENCES QUIZ(ID),
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS OPCAO(
	ID INT NOT NULL AUTO_INCREMENT,
    DESCRICAO TEXT,
    OPCAO ENUM("A", "B", "C", "D"),
    CORRETA ENUM("S", "N"),
    QUIZ INT,
    PERGUNTA INT,
    FOREIGN KEY (QUIZ) REFERENCES QUIZ(ID),
    FOREIGN KEY (PERGUNTA) REFERENCES PERGUNTA(ID),
    PRIMARY KEY(ID)
);

INSERT INTO QUIZ VALUES (NULL, "DESENVOLVIMENTO", "Quiz rápido sobre desenvolvimento");

INSERT INTO PERGUNTA VALUES (NULL, "1. Qual das opções abaixo é uma linguagem de programação?", 1);
INSERT INTO PERGUNTA VALUES (NULL, "2. O que significa o termo CSS?", 1);
INSERT INTO PERGUNTA VALUES (NULL, "3. MySQL é um exemplo de banco de dados RELACIONAL.", 1);

INSERT INTO OPCAO VALUES (NULL, "CSRF", "A", "N", 1, 1);
INSERT INTO OPCAO VALUES (NULL, "JSON", "B", "N", 1, 1);
INSERT INTO OPCAO VALUES (NULL, "JWT", "C", "N", 1, 1);
INSERT INTO OPCAO VALUES (NULL, "JAVASCRIPT", "D", "S", 1, 1);

INSERT INTO OPCAO VALUES (NULL, "Carret Super Style", "A", "N", 1, 2);
INSERT INTO OPCAO VALUES (NULL, "Cascading Style Sheets", "B", "S", 1, 2);
INSERT INTO OPCAO VALUES (NULL, "Cobol Spyke Sparrow", "C", "N", 1, 2);
INSERT INTO OPCAO VALUES (NULL, "Cast Style Sheets", "D", "N", 1, 2);

INSERT INTO OPCAO VALUES (NULL, "FALSO", "A", "N", 1, 3);
INSERT INTO OPCAO VALUES (NULL, "VERDADEIRO", "B", "S", 1, 3);